export type StorySpeaker = "mio" | "suzune" | "player" | "narrator";
export type StoryFocus = "mio" | "suzune" | "both" | "none";

export type StoryLine = {
  speaker: StorySpeaker;
  text: string;
  focus?: StoryFocus;
  visible?: Array<"mio" | "suzune">;
  cue?: string;
};

export type StoryChapter = {
  id: string;
  episode: string;
  title: string;
  subtitle: string;
  location: string;
  summary: string;
  background: string;
  lines: StoryLine[];
};

export const STORY_SEASON_TITLE = "星海棋社的春日来信";

export const STORY_SEASON_ONE: StoryChapter[] = [
  {
    id: "late-newcomer",
    episode: "第一话",
    title: "迟到的新成员",
    subtitle: "一局还没开始的棋，也会等它的玩家。",
    location: "星海棋社 · 午后",
    summary: "四月的最后一场社团招新，你推开了那扇差点错过的门。",
    background: "/micosm-club-lobby-desktop.webp",
    lines: [
      { speaker: "narrator", text: "四月的最后一场社团招新已经结束。走廊尽头，只有一扇门还亮着灯。", focus: "none", visible: [] },
      { speaker: "suzune", text: "等一下！你是来找星海棋社的吗？太好了，我还没有把招新牌收起来。", focus: "suzune", visible: ["suzune"] },
      { speaker: "player", text: "我只是来看看。我下得不算好，也没有参加过正式对局。", focus: "suzune", visible: ["suzune"] },
      { speaker: "suzune", text: "那正合适。这里最不缺会下棋的人，缺的是愿意坐下来的人。", focus: "suzune", visible: ["suzune"] },
      { speaker: "mio", text: "铃音，别堵在门口。让客人先坐。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "窗边的黑发女生放下棋谱。她面前的棋盘上，只摆着一颗黑子。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "藤原澪，棋社部长。你可以把这里当成一次普通的下午。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "player", text: "普通的下午，为什么棋盘上只有一颗棋子？", focus: "both", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "因为部长说，第二颗要留给今天最后一个走进来的人。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "坐吧。黑白随你，也不计胜负。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "你伸手碰到棋盒时，窗外的风恰好掀起了报名表的一角。", focus: "both", visible: ["mio", "suzune"], cue: "棋子轻响" },
      { speaker: "suzune", text: "欢迎来到 Micosm Game，也欢迎来到星海棋社。以后请多指教啦。", focus: "suzune", visible: ["mio", "suzune"] },
    ],
  },
  {
    id: "rain-first-move",
    episode: "第二话",
    title: "雨声与第一手",
    subtitle: "落子之前，先听一会儿雨。",
    location: "星海棋社 · 雨天",
    summary: "第一次值日、第一杯热茶，以及一盘被雨声放慢的围棋。",
    background: "/story/scene-go.webp",
    lines: [
      { speaker: "narrator", text: "入社后的第三天，骤雨把整座校园困在了傍晚。棋社里只有你和藤原澪。", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "你已经盯着右上角三分钟了。那里不会因为被注视就变成好点。", focus: "mio", visible: ["mio"] },
      { speaker: "player", text: "我怕下错。", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "下错也是一手。一直不下，才什么都不会留下。", focus: "mio", visible: ["mio"] },
      { speaker: "narrator", text: "你落下一子。她没有立刻回应，而是把一杯热茶推到你手边。", focus: "mio", visible: ["mio"], cue: "雨声渐密" },
      { speaker: "player", text: "部长对每个新成员都这么耐心吗？", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "不。我只是刚好不讨厌雨天，也不讨厌这盘棋。", focus: "mio", visible: ["mio"] },
      { speaker: "suzune", text: "我回来啦！便利店的伞只剩一把，所以我顺便带了三份布丁。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "伞和布丁之间没有因果关系。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "有的。没有伞会淋雨，淋雨的人需要布丁。逻辑闭环。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "player", text: "那这盘棋怎么办？", focus: "both", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "封盘。雨停以后继续。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "那天的雨一直下到闭社。棋没有分出胜负，三份布丁倒是都没有剩下。", focus: "both", visible: ["mio", "suzune"] },
    ],
  },
  {
    id: "world-channel-letter",
    episode: "第三话",
    title: "世界频道的挑战书",
    subtitle: "最吵闹的消息，也可能藏着认真的期待。",
    location: "线上大厅 · 夜间",
    summary: "一条误发到世界频道的约战，让棋社迎来久违的公开交流赛。",
    background: "/micosm-club-lobby-desktop.webp",
    lines: [
      { speaker: "suzune", text: "完了。我本来想私聊隔壁学校的社长，结果把挑战书发进世界频道了。", focus: "suzune", visible: ["suzune"] },
      { speaker: "player", text: "下面已经有二十个人回复“应战”了。", focus: "suzune", visible: ["suzune"] },
      { speaker: "suzune", text: "所以我决定装作这就是原计划。你觉得自然吗？", focus: "suzune", visible: ["suzune"] },
      { speaker: "mio", text: "不自然。不过挑战已经收到，就认真准备。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "player", text: "我也要上场？", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "你加入了棋社，当然有自己的位置。胜负不是门票。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "而且名单已经交了。你的名字排在第三个，撤不回来。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "player", text: "你什么时候写上去的？", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "在你问“我也要上场”之前。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "世界频道仍在不断弹出新消息。藤原澪却关掉面板，把一张棋谱放到你面前。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "从现在开始，每晚复盘一局。我陪你。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "那我负责夜宵和气氛。我们三个，正好是一支小队。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "原本仓促的挑战，就这样变成了你们共同等待的第一个周末。", focus: "both", visible: ["mio", "suzune"] },
    ],
  },
  {
    id: "rooftop-practice",
    episode: "第四话",
    title: "天台练习赛",
    subtitle: "风会吹乱棋谱，但吹不走已经记住的那一手。",
    location: "天文台天台 · 午休",
    summary: "白石铃音把练习地点搬上天台，也把她藏起来的紧张说了出来。",
    background: "/story/scene-gomoku.webp",
    lines: [
      { speaker: "narrator", text: "交流赛前一天，白石铃音抱着棋盘，把你带到天文台的露台。", focus: "suzune", visible: ["suzune"] },
      { speaker: "suzune", text: "室内太安静了。越安静，我越能听见自己在紧张。", focus: "suzune", visible: ["suzune"] },
      { speaker: "player", text: "原来你也会紧张。", focus: "suzune", visible: ["suzune"] },
      { speaker: "suzune", text: "当然会。我只是习惯在别人发现以前先笑出来。", focus: "suzune", visible: ["suzune"] },
      { speaker: "player", text: "那今天不用负责气氛。我们安静下一盘。", focus: "suzune", visible: ["suzune"] },
      { speaker: "narrator", text: "她愣了一下，随后把第一颗黑子落在棋盘中央。", focus: "suzune", visible: ["suzune"], cue: "风铃轻响" },
      { speaker: "suzune", text: "好。不过输的人要请对方喝汽水。", focus: "suzune", visible: ["suzune"] },
      { speaker: "mio", text: "那你们可能要先把被风吹走的棋谱捡回来。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "部长？你不是说午休不过来吗？", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "我来送固定棋谱的夹子。顺便提醒你们，还有七分钟上课。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "player", text: "这盘还没下完。", focus: "both", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "那就记住局面，放学后继续。欠我的汽水也记得。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "你们跑下楼时，藤原澪留在原地，把散落的棋谱一张张夹好。", focus: "mio", visible: ["mio"] },
    ],
  },
  {
    id: "unmailed-record",
    episode: "第五话",
    title: "没有寄出的棋谱",
    subtitle: "有些话写在棋盘上，反而更难寄出去。",
    location: "棋社资料室 · 星夜",
    summary: "整理旧柜子时，你发现了一份没有署名、也没有寄出的棋谱。",
    background: "/story/scene-reversi.webp",
    lines: [
      { speaker: "narrator", text: "交流赛因暴雨延期。你留下整理资料，在旧棋谱里发现一只没有封口的信封。", focus: "none", visible: [] },
      { speaker: "player", text: "“给那个总是犹豫很久才落子的人”……这是写给谁的？", focus: "none", visible: [] },
      { speaker: "mio", text: "大概是写给一个还没有出现的人。", focus: "mio", visible: ["mio"] },
      { speaker: "player", text: "部长什么时候站在后面的？", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "在你念出第一句的时候。那是我刚接任部长时留下的棋谱。", focus: "mio", visible: ["mio"] },
      { speaker: "player", text: "为什么没有寄？", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "因为当时不知道收件人是谁。只是觉得，总有一天会有人需要它。", focus: "mio", visible: ["mio"] },
      { speaker: "narrator", text: "信封里是一盘残局。最后一手的位置空着，旁边写着：不要替别人决定答案。", focus: "mio", visible: ["mio"] },
      { speaker: "player", text: "现在找到收件人了吗？", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "也许。等他自己把最后一手下完，我才能确定。", focus: "mio", visible: ["mio"] },
      { speaker: "suzune", text: "你们两个躲在这里说什么秘密？我带了延期补偿用的关东煮。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "没有秘密。只是找到了一份该重新摆出来的棋谱。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "你把信封收进随身的棋谱夹。那一晚，最后一手仍然空着。", focus: "both", visible: ["mio", "suzune"] },
    ],
  },
  {
    id: "before-the-festival",
    episode: "第六话",
    title: "星海祭前夜",
    subtitle: "把灯一盏盏点亮，就像把彼此的名字连成星座。",
    location: "星海棋社 · 深夜",
    summary: "公开棋会前的最后准备，三个人在空教室里完成了第一张合照。",
    background: "/micosm-club-lobby-desktop.webp",
    lines: [
      { speaker: "suzune", text: "横幅再往左一点。不对，刚才那里更好。要不还是右边？", focus: "suzune", visible: ["suzune"] },
      { speaker: "player", text: "这是你第六次改变主意。", focus: "suzune", visible: ["suzune"] },
      { speaker: "mio", text: "第八次。你漏算了拿梯子之前的两次。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "重要活动当然要认真。明天会有很多第一次走进棋社的人。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "player", text: "像我那天一样？", focus: "both", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "不完全一样。那天我们特意为你留了一颗棋子。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "等一下，这件事原来不是巧合？部长你瞒得好深。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "招新最后一天，总该为迟到的人留一个位置。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "白石铃音把相机架在棋柜上，十秒倒计时开始闪烁。", focus: "both", visible: ["mio", "suzune"], cue: "相机倒计时" },
      { speaker: "suzune", text: "快靠近一点！这可是星海棋社新学期的第一张合照。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "player", text: "部长，你在笑吗？", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "没有。是快门太慢了。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "照片里，她的嘴角确实扬起了一点。后来那张照片被放在了大厅最显眼的位置。", focus: "both", visible: ["mio", "suzune"] },
    ],
  },
  {
    id: "celestial-board-festival",
    episode: "第七话",
    title: "星海棋会",
    subtitle: "胜负写在结果里，同行的人写在记忆里。",
    location: "天文台会场 · 晴日",
    summary: "公开棋会终于开始。比起名次，你们更想守住那个为后来者留下的位置。",
    background: "/story/scene-gomoku.webp",
    lines: [
      { speaker: "narrator", text: "活动当天，天文台露台摆满棋盘。世界频道里约战的人，真的一个接一个来了。", focus: "both", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "十号桌需要裁判，十三号桌要补棋子，还有人问洗手间在哪里！", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "铃音，先呼吸。十号桌交给我，十三号桌交给他。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "player", text: "那洗手间呢？", focus: "both", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "终于有一个我能立刻解决的问题。跟我来！", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "午后，你完成了自己的交流对局。最后一手落下时，没有掌声，只有对手伸来的手。", focus: "none", visible: [] },
      { speaker: "player", text: "结果不算漂亮。", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "但你没有逃开任何一手。对第一次公开对局来说，这已经足够漂亮。", focus: "mio", visible: ["mio"] },
      { speaker: "suzune", text: "而且我们拿到了今天最重要的东西。看，新的入社申请表！", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "player", text: "有七个人？", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "八个。最后一个说他还不太会下，只想先来看看。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "那就给他留一个位置。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "夕阳落在空着的棋盘中央。你忽然明白，那颗被留下的棋子从来不只属于一个人。", focus: "both", visible: ["mio", "suzune"] },
    ],
  },
  {
    id: "last-train-home",
    episode: "最终话",
    title: "末班车之前",
    subtitle: "春天会结束，但下一手还在等你。",
    location: "棋社与车站之间 · 月夜",
    summary: "棋会结束后的归途，未完成的残局终于等到了它的最后一手。",
    background: "/story/scene-reversi.webp",
    lines: [
      { speaker: "narrator", text: "收拾完会场时，末班车只剩二十分钟。白石铃音先一步抱着横幅跑向车站。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "suzune", text: "我去占自动售货机旁边的位置！你们两个别又走着走着开始复盘。", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "她今天说了太多话，明天大概会失声。", focus: "mio", visible: ["mio"] },
      { speaker: "player", text: "部长，你其实很高兴吧。", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "嗯。比预想中更高兴。", focus: "mio", visible: ["mio"] },
      { speaker: "narrator", text: "她停在路灯下，从书包里取出那只没有封口的信封。", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "最后一手，你想好了吗？", focus: "mio", visible: ["mio"] },
      { speaker: "player", text: "想好了。但我不打算现在告诉你。", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "为什么？", focus: "mio", visible: ["mio"] },
      { speaker: "player", text: "因为下次值日，我们可以把那盘棋重新摆一遍。我想当面下给你看。", focus: "mio", visible: ["mio"] },
      { speaker: "narrator", text: "藤原澪安静地看了你几秒，随后重新收好信封。", focus: "mio", visible: ["mio"] },
      { speaker: "mio", text: "好。我会等你。不是以部长的身份，只是作为你的对手。", focus: "mio", visible: ["mio"] },
      { speaker: "suzune", text: "你们还要聊多久？末班车可不会同意悔棋！", focus: "suzune", visible: ["mio", "suzune"] },
      { speaker: "mio", text: "走吧。明天见。", focus: "mio", visible: ["mio", "suzune"] },
      { speaker: "narrator", text: "你们朝车站跑去。月光落在三个人的影子上，像一条还没有走完的星轨。", focus: "both", visible: ["mio", "suzune"], cue: "第一季 完" },
    ],
  },
];
